In [1]:
import pyclesperanto_prototype as cle
import numpy as np

cle.__version__

'0.23.6'

# Minimal example demonstrating the bug that occurs when using `np.flip()` on a cle.array created by cle.create()

In [2]:
cle_array = cle.create((2, 3))
cle_array[0] = cle.asarray(np.arange(3))
cle_array[1] = cle.asarray(np.arange(3, 6))
cle_array

cl.OCLArray([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [3]:
np.flip(cle_array, axis=0)


cl.OCLArray([[3., 4., 5.],
       [0., 1., 2.]], dtype=float32)

In [4]:
np.flip(cle_array, axis=1)

cl.OCLArray([[2., 1., 0.],
       [5., 4., 3.]], dtype=float32)

## With a numpy array the code works as expected

In [5]:
np_array = np.zeros((2, 3))
np_array[0] = np.arange(3)
np_array[1] = np.arange(3, 6)
np_array

array([[0., 1., 2.],
       [3., 4., 5.]])

In [6]:
np.flip(np_array, axis=0)


array([[3., 4., 5.],
       [0., 1., 2.]])

In [7]:
np.flip(np_array, axis=1)

array([[2., 1., 0.],
       [5., 4., 3.]])