# Lists of nonzero pixel coordinates
When working with adjacency matrices (also known as touch-matrices, proximal-neighbor-matrices and n-nearest-neighbor matrices) and also with images resulting from minima and maxima detection, a common task is to retrieve lists of coordinates from a given input image where the input image contained non-zero values. In numpy, the corresponding operation is called [nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html) and in clesperanto the function [spots_to_pointlist](https://clij.github.io/clij2-docs/reference_spotsToPointList) does the same. `spots_to_pointlist` assumes a binary image as input which only contains `1` and `0` though.

**Note**: A major difference between numpy and clesperanto becomes apparent in this case: clesperanto's dimension ordering/naming is different: While `np.nonzero` returns this list of coordinates:
```
[[y0,y1,y2],[x0,x1,x2]]
```
clesperanto will return this list:
```
[[x0,x1,x2],[y0,y1,y2]]
```
Use `cle.flip(pointlist, flip_x=False)` to convert a `pointlist` retrieved from clesperanto to one that equals the list in numpy.

In [1]:
import numpy as np
import pyclesperanto_prototype as cle

cle.get_device()

<gfx90c on Platform: AMD Accelerated Parallel Processing (2 refs)>

## 2D case

In [2]:
label_image = np.asarray([
    [1,0,0,1],
    [0,0,1,0],
    [0,1,0,0]
])
print(label_image)

[[1 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [3]:
label_image.nonzero()

(array([0, 0, 1, 2], dtype=int64), array([0, 3, 2, 1], dtype=int64))

In [4]:
cl_label_image = cle.push(label_image)
print(cl_label_image)

[[1. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [5]:
cle.spots_to_pointlist(cl_label_image)

cl.Array([[0., 3., 2., 1.],
       [0., 0., 1., 2.]], dtype=float32)

In [6]:
cle.flip(cle.spots_to_pointlist(cl_label_image), flip_x=True)

cl.Array([[2., 1., 0., 0.],
       [1., 2., 3., 0.]], dtype=float32)

## 3D case

In [7]:
label_image = np.asarray([[
        [1,0,0,1],
        [0,0,1,0],
        [0,1,0,0]
    ],[
        [0,0,0,0],
        [0,1,0,0],
        [0,0,0,0]
]])
print(label_image)

[[[1 0 0 1]
  [0 0 1 0]
  [0 1 0 0]]

 [[0 0 0 0]
  [0 1 0 0]
  [0 0 0 0]]]


In [8]:
label_image.nonzero()

(array([0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 2, 1], dtype=int64),
 array([0, 3, 2, 1, 1], dtype=int64))

In [9]:
cl_label_image = cle.push(label_image)
print(cl_label_image)

[[[1. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
cle.spots_to_pointlist(cl_label_image)

cl.Array([[0., 3., 2., 1., 1.],
       [0., 0., 1., 2., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [11]:
cle.flip(cle.spots_to_pointlist(cl_label_image), flip_x=False)

cl.Array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 2., 1.],
       [0., 3., 2., 1., 1.]], dtype=float32)