In [1]:
import scipy.ndimage as ndi
import numpy as np
import pyclesperanto_prototype as cle

In [2]:
array3d = np.random.rand(100, 100, 100)
array3d[11, 6, 0] = 1
array3d[10, 48, 0] = 1

In [3]:
print(ndi.maximum_position(array3d))
print(cle.maximum_position(array3d))

(10, 48, 0)
(10, 48, 0)


In [4]:
array2d = np.random.rand(100, 80)
array2d[89, 2] = 1
array2d[90, 40] = 1

In [5]:
print(ndi.maximum_position(array2d))
print(cle.maximum_position(array2d))

(89, 2)
(89, 2)


In [6]:
array1d = np.random.rand(100)
array1d[56] = 1
array1d[20] = 1

In [7]:
print(ndi.maximum_position(array1d))
print(cle.maximum_position(array1d))

(20,)
(20,)


In [8]:
array = np.random.randint(0, 10, (30, 50, 20))
array[20, 48, 19] = 10

dims = np.array(np.asarray(array).shape)
# see numpy.unravel_index to understand this line.
dim_prod = np.cumprod([1] + list(dims[:0:-1]))[::-1]

print(dims)
print(dim_prod)
positions = np.arange(array.size).reshape(array.shape)

result = []
result += [array.max()]
result += [positions[array == array.max()][0]]

print(result)

[30 50 20]
[1000   20    1]
[10, 20979]


In [9]:
array = np.random.randint(0, 10, (5, 8, 3))
dimensionality = array.shape
print(dimensionality)
print(array)
temp_max = cle.create([1, dimensionality[1], dimensionality[0]])
pos_x = cle.create([1, dimensionality[1], dimensionality[0]])

temp_max = cle.maximum_x_projection(array)
cle.x_position_of_maximum_x_projection(array, pos_x)
print(temp_max)

source = temp_max
pos_y = cle.create([1, 1, dimensionality[0]])
temp_max = cle.maximum_y_projection(array, temp_max)
cle.y_position_of_maximum_y_projection(array, pos_y)
print(temp_max)

source = temp_max
pos_z = cle.create([1, 1, 1])
temp_max = cle.maximum_z_projection(array, temp_max)
cle.z_position_of_maximum_z_projection(array, pos_z)
print(temp_max)


(5, 8, 3)
[[[7 4 1]
  [3 9 4]
  [9 3 2]
  [2 7 2]
  [1 3 6]
  [1 2 7]
  [0 4 7]
  [3 6 2]]

 [[4 9 2]
  [1 4 8]
  [9 7 3]
  [2 9 4]
  [3 3 6]
  [7 3 8]
  [1 3 7]
  [5 9 0]]

 [[9 9 3]
  [3 3 9]
  [3 7 0]
  [6 2 2]
  [6 1 7]
  [0 9 8]
  [5 6 4]
  [1 6 7]]

 [[5 5 5]
  [7 0 0]
  [3 0 5]
  [5 4 6]
  [8 6 9]
  [1 1 8]
  [7 2 7]
  [1 2 1]]

 [[2 6 7]
  [8 6 9]
  [0 1 7]
  [8 4 5]
  [8 7 1]
  [6 4 0]
  [4 3 4]
  [8 3 9]]]
[[7. 9. 9. 5. 7.]
 [9. 8. 9. 7. 9.]
 [9. 9. 7. 5. 7.]
 [7. 9. 6. 6. 8.]
 [6. 6. 7. 9. 8.]
 [7. 8. 9. 8. 6.]
 [7. 7. 6. 7. 4.]
 [6. 9. 7. 2. 9.]]
[[9. 9. 7. 7. 7.]
 [9. 9. 8. 8. 8.]
 [9. 9. 9. 9. 9.]
 [8. 6. 9. 9. 9.]
 [8. 7. 9. 9. 9.]
 [8. 7. 9. 9. 9.]
 [8. 7. 9. 9. 9.]
 [8. 7. 9. 9. 9.]]
[[9. 9. 7. 7. 7.]
 [8. 9. 9. 9. 9.]
 [9. 7. 7. 7. 7.]
 [8. 9. 6. 6. 6.]
 [8. 7. 9. 9. 9.]
 [7. 9. 8. 8. 8.]
 [7. 6. 7. 7. 7.]
 [8. 9. 9. 9. 9.]]


In [10]:
array = np.random.randint(0, 10, (6, 8))
dimensionality = array.shape

print(array)

temp_max = cle.create([dimensionality[0], 1])
pos_x = cle.create([dimensionality[0], 1])

print(cle.maximum_x_projection(array))
cle.maximum_x_projection(array, temp_max)
print(temp_max)

[[9 2 2 2 2 5 4 9]
 [3 4 3 1 1 5 1 6]
 [7 7 1 2 6 3 8 4]
 [5 4 9 2 7 9 6 4]
 [8 6 5 8 4 2 3 5]
 [3 3 5 2 3 6 5 2]]
[[9.]
 [6.]
 [8.]
 [9.]
 [8.]
 [6.]]
[[9.]
 [6.]
 [8.]
 [9.]
 [8.]
 [6.]]


In [11]:
array = np.random.randint(0, 10, (6, 8))
max_ = cle.maximum_x_projection(array)
print(max_)

max_ = cle.maximum_y_projection(max_)
print(max_)

[[7.]
 [9.]
 [6.]
 [9.]
 [9.]
 [9.]]
[[9.]]


In [12]:
array3d = np.random.randint(0, 10, (6, 4, 3))
array3d[4, 2, 0] = 10

temp = cle.maximum_x_projection(array3d)
x_pos = cle.x_position_of_maximum_x_projection(array3d)
source = temp

temp = cle.maximum_y_projection(source)
y_pos = cle.y_position_of_maximum_y_projection(source)
source = temp

z_pos = cle.x_position_of_maximum_x_projection(source)

z_coord = int(z_pos[0][0])
y_coord = int(y_pos[0][z_coord])
x_coord = int(x_pos[y_coord][z_coord])

print(z_coord, y_coord, x_coord)

4 2 0
